version: 2.1

jobs:
  arduino-ci-test:
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - run:
          name: Install
          command:
            bundle install
      - run:
          name: Test
          command:
            bundle exec arduino_ci_remote.rb | tee /tmp/test_output.txt
          no_output_timeout: 1m
      - store_artifacts:
            path: /tmp/test_output.txt
            destination: test_output
      - store_test_results:
          path: test/reports

workflows:
  arduino-ci-workflow:
    jobs:
      - arduino-ci-test
